<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

  <!-- ====== params (meters) ====== -->
  <xacro:property name="wheel_radius" value="0.045"/>          <!-- 4.5cm -->
  <xacro:property name="wheel_sep"    value="0.23"/>           <!-- left-right wheel center distance 23cm -->
  <xacro:property name="base_height"  value="0.45"/>           <!-- bottom to top 45cm -->
  <xacro:property name="base_length"  value="0.21"/>           <!-- caster +-10.5cm => length ~21cm -->
  <xacro:property name="base_width"   value="0.23"/>           <!-- 대략 wheel_sep와 유사 -->
  <xacro:property name="lidar_diam"   value="0.06"/>           <!-- 6cm -->
  <xacro:property name="lidar_h_from_ground" value="0.44"/>    <!-- 바닥 기준 라이다 위치 44cm -->

  <!-- base_link는 "바퀴 축 높이" 기준 -->
  <!-- base_footprint(바닥) -> base_link(축 높이) -->
  <link name="base_footprint"/>

  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child  link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <!-- 바닥~상단 45cm 박스가 바닥에서 시작한다고 가정 -->
      <!-- base_link는 축 높이(4.5cm)이므로 박스 중심은 (0.45/2 - 0.045)=0.18m -->
      <origin xyz="0 0 ${base_height/2 - wheel_radius}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2 - wheel_radius}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- wheels (visual only for now) -->
  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/> <!-- cylinder axis -> y -->
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.02"/>
      </geometry>
    </visual>
  </link>

  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.02"/>
      </geometry>
    </visual>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="left_wheel_link"/>
    <origin xyz="0 ${wheel_sep/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="right_wheel_link"/>
    <origin xyz="0 ${-wheel_sep/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- caster (대충 표시만) -->
  <link name="front_caster_link">
    <visual>
      <geometry><sphere radius="0.015"/></geometry>
    </visual>
  </link>
  <joint name="front_caster_joint" type="fixed">
    <parent link="base_footprint"/>
    <child  link="front_caster_link"/>
    <origin xyz="0.105 0 0.015" rpy="0 0 0"/> <!-- +10.5cm -->
  </joint>

  <link name="rear_caster_link">
    <visual>
      <geometry><sphere radius="0.015"/></geometry>
    </visual>
  </link>
  <joint name="rear_caster_joint" type="fixed">
    <parent link="base_footprint"/>
    <child  link="rear_caster_link"/>
    <origin xyz="-0.105 0 0.015" rpy="0 0 0"/> <!-- -10.5cm -->
  </joint>

  <!-- ====== LiDAR frame ====== -->
  <!-- 바닥 기준 44cm인데 base_link는 바닥에서 4.5cm 위 => base_link 기준 z = 0.44 - 0.045 = 0.395 -->
  <link name="laser_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_diam/2}" length="0.06"/>
      </geometry>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="laser_frame"/>
    <origin xyz="0.005 0 ${lidar_h_from_ground - wheel_radius}" rpy="0 0 0"/> <!-- x=+0.5cm, y=0 -->
  </joint>

</robot>
